# Generated by Django 2.2.5 on 2019-09-05 10:44

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20190905_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id_student', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('мужчина', 'мужчина'), ('женщина', 'женщина')], max_length=8)),
                ('grade_point_average', models.FloatField(default=None)),
                ('birthday', models.DateField()),
                ('marital_status', models.CharField(choices=[('не женат', 'не женат'), ('не замужем', 'не замужем'), ('женат', 'женат'), ('замужем', 'замужем')], max_length=11)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('email', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=200)),
                ('avatar', models.ImageField(upload_to=blog.models.generate_file_name)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
