# Generated by Django 2.2.5 on 2019-09-05 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190905_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='use',
            name='grade_point_average',
        ),
    ]
