# Generated by Django 2.2.5 on 2019-09-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_use_grade_point_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='use',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
