# Generated by Django 2.2.5 on 2019-09-05 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_use_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='use',
            old_name='id_student',
            new_name='id_use',
        ),
    ]
